### ISSUE TITLE
Plugin manager in the snap version

### ISSUE THREAD

**Issue by igorljubuncic** [mmtrt/notepad-plus-plus#10] opened 2018-11-05 14:36 UTC
I am testing N++ snap version. I encountered two issues:

Plugin manager is not installed - I had to manually install it via settings > import.
Once installed, the plugin manager does not connect to the web:

There was an error downloading the plugin list. Please check your Internet connection, and your proxy settings in Internet Explorer, Edge or Chrome

![notepadpp-plugin-manager-no-network](https://user-images.githubusercontent.com/43789966/48003899-aab7e800-e107-11e8-9dfd-ddbf6b267066.png)

The network interface is connected:

snap interfaces notepad-plus-plus
:network gimp,lxd,notepad-plus-plus,review-tools,vlc

**Comment by mmtrt** [comment] 2018-11-05 15:46
Try the solution I posted in issue #1 see if that fixes.

**Comment by igorljubuncic** [comment] 2018-11-05 16:03
Forcing HTTP fixes it. Would it be possible to tweak the plugin manager to work with HTTPS?

**Comment by mmtrt** [comment] 2018-11-05 19:50
fix has been released and the issue is resolved now also make sure you remove `wineprefix` in order to install needed packages to it.

`$HOME/snap/notepad-plus-plus/common/.wine`

**Closed by mmtrt** 2018-11-05 19:50 UTC
